### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by kaste**
Hi! We want to change the signature of `__init__`, this would break your plugin, and while I'm here I make following suggestions.

I coded this in the Github editor so it might be not completely okay. Also no docs bc I can only edit one file here anyway.

- The common setting for the binary is called `executable`. `executable` is built into SublimeLinter and could replace your 'livecode-server-path'. The default here would be 'livecode-community-server' and if it's on PATH the user would be ready to go without editing the settings.

- 'scope' and 'explicitVariable' are normal cli args and can be expressed within `defaults`. But users must then use this longer name instead of 'explicitvars'

- Removed some deprecated members and the ones holding the default values.

:wave:

### CODE REVIEW

**Comment by trevordevore** [comment]
@kaste Thanks for the PR and feedback! I'm merging this in now.

**Comment by kaste** [comment]
:tada: Glad it worked out

**Comment by trevordevore** [comment]
@kaste - is it possible to configure this plugin to pass different parameters to the executable based on the current language? The LiveCode linger supports both LiveCode Script and LiveCode Builder. These are two different types of source files. 

If not then I suppose I will create a separate GitHub repo with LiveCode Builder Support.

**Comment by kaste** [comment]
Yes sure. The approach depends on how different the commands actually are.

E.g. you can just expose/define two classes in linter.py. Then people install only this one package, but get effectively two linters and can configure them separately. 

But you can also add source.livecodebuilder to the selector, then this linter runs on different views with different syntaxes.

**Comment by trevordevore** [comment]
I went with adding a second class to linter.py. That was easy!

**Comment by kaste** [comment]
👍 bc so it stays declarative/pure configuration.

**Pull request merged**
